### ISSUE TITLE
Shader breaks in Play Mode

### ISSUE THREAD

**Issue by robotTX1** [happy-turtle/foliage-wind#2]
Hey,

First of all thank you for your updated shader, but unfortunately the URP shader breaks in play mode. Everything looks correct in edit mode and in the game preview when the game is not running, but when I start the game the trees go crazy.
Could you help resolve this issue? Did I forget to set something?

Here is a video where you can see the problem: [https://youtu.be/2Mxja4dCNtQ](https://youtu.be/2Mxja4dCNtQ)

Sincerelly,
robotTX

URP settings:
<img width="608" alt="image1" src="https://user-images.githubusercontent.com/84637366/214870075-b039ddec-5339-423a-a65c-411bf3f893ca.PNG">
<img width="597" alt="image2" src="https://user-images.githubusercontent.com/84637366/214870079-8484b874-79fc-4257-a73b-09bee1ad364b.PNG">
<img width="585" alt="image3" src="https://user-images.githubusercontent.com/84637366/214870081-ed1b23b0-c32e-4fd8-beda-0ec0c94c1bb0.PNG">
<img width="608" alt="image4" src="https://user-images.githubusercontent.com/84637366/214870083-ad22bc86-049f-4271-8284-c3c173ed5386.PNG">
<img width="610" alt="image5" src="https://user-images.githubusercontent.com/84637366/214870085-710227fc-61fe-41a0-bc05-a3ae6cb1c0f8.PNG">
<img width="603" alt="image6" src="https://user-images.githubusercontent.com/84637366/214870091-85ddd241-254f-4a8b-b935-19faf229e0cc.PNG">
<img width="607" alt="image7" src="https://user-images.githubusercontent.com/84637366/214870093-6b330993-aa1e-4c4a-852d-89aa7da52f0e.PNG">

**Comment by happy-turtle** [comment]
Hi, thanks for trying it out. I wouldn't even know where to get the Book of the Dead assets anymore.

This is probably an error caused by different time scales. This is the only thing different between play mode and edit mode. See [line 18](https://github.com/happy-turtle/foliage-wind/blob/URP/Scripts/WindControlPass.cs#L18) and [line 39](https://github.com/happy-turtle/foliage-wind/blob/URP/Scripts/WindControlPass.cs#L39). Only using Time.time might do the trick since it is scaled by timeScale. Unfortunately I do not remember why there is a differentiation between edit mode and play mode. A perfect example for when you should put a comment in your code.

**Comment by robotTX1** [comment]
Hi,

In the mean time, I figured out if I set the gameobject that has the mesh renderer to static then the trees go crazy. I turned off static and it works perfectly. I got the Book of the Dead project from a Github repo.
Thanks for making the shader compatible with URP it is a huge help.

**Comment by happy-turtle** [comment]
> Hi,
> 
> In the mean time, I figured out if I set the gameobject that has the mesh renderer to static then the trees go crazy. I turned off static and it works perfectly. I got the Book of the Dead project from a Github repo.
> Thanks for making the shader compatible with URP it is a huge help.

Ah alright, glad you found a fix. [Static batching](https://docs.unity3d.com/Manual/static-batching.html) won't work, because with static batching all static objects share their vertex information. The wind effect is based on individual vertex displacement for every tree though. So it will probably cause problems. If you need any other static flag just disable only static batching for your trees.

Thanks for the tip on how to find the old assets, good point 😄

**Comment by robotTX1** [comment]
Thanks for your answer and your help!

With your explanation it's clear why it didn't work as expected.
Here is the book of the dead repository in case you need it: [https://github.com/Delacrowa/book-of-the-dead-environment-hdrp](https://github.com/Delacrowa/book-of-the-dead-environment-hdrp)
